------- User table creation -----

CREATE TABLE USER (
  USERNAME VARCHAR(32) PRIMARY KEY,
  PASSWORD CHAR(64) NOT NULL,
  USER_TYPE VARCHAR(32) NOT NULL
);

CREATE TABLE ROLES (
  ID INT(32) PRIMARY KEY,
  NAME VARCHAR(20) NOT NULL
);